name: Local Build Test

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Service to build (frontend or backend)"
        required: true
        default: "frontend"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Service
        id: build
        env:
          # Backend-specific environment variables
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_BOT_USERNAME: ${{ secrets.TWITTER_BOT_USERNAME }}
          PERPLEXITY_API_URL: ${{ secrets.PERPLEXITY_API_URL }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          # Service-specific configuration
          if [ "${{ github.event.inputs.service }}" = "frontend" ]; then
            DOCKERFILE="./frontend/src/Dockerfile"
            CONTEXT="./frontend/src"
            BUILD_ARGS="--build-arg NEXT_PUBLIC_API_URL=http://focustbackend:8000 \
                        --build-arg BUILD_VERSION=1.0.0 \
                        --build-arg BUILD_TIMESTAMP=$(date +'%Y-%m-%d')"
          else
            DOCKERFILE="./backend/Dockerfile"
            CONTEXT="./backend"
            BUILD_ARGS="--build-arg TWITTER_BEARER_TOKEN=$TWITTER_BEARER_TOKEN \
                        --build-arg TWITTER_CONSUMER_KEY=$TWITTER_CONSUMER_KEY \
                        --build-arg TWITTER_CONSUMER_SECRET=$TWITTER_CONSUMER_SECRET \
                        --build-arg TWITTER_ACCESS_TOKEN=$TWITTER_ACCESS_TOKEN \
                        --build-arg TWITTER_ACCESS_TOKEN_SECRET=$TWITTER_ACCESS_TOKEN_SECRET \
                        --build-arg TWITTER_BOT_USERNAME=$TWITTER_BOT_USERNAME \
                        --build-arg PERPLEXITY_API_URL=$PERPLEXITY_API_URL \
                        --build-arg PERPLEXITY_API_KEY=$PERPLEXITY_API_KEY \
                        --build-arg DB_HOST=$DB_HOST \
                        --build-arg DB_PORT=$DB_PORT \
                        --build-arg DB_USER=$DB_USER \
                        --build-arg DB_PASSWORD=$DB_PASSWORD"
          fi

          # Verify directory exists
          if [ ! -d "$CONTEXT" ]; then
            echo "${{ github.event.inputs.service }} source directory not found!"
            exit 1
          fi

          # Build image (no push)
          DOCKER_BUILDKIT=1 docker build \
            $BUILD_ARGS \
            -t focust-${{ github.event.inputs.service }}:local \
            -f $DOCKERFILE $CONTEXT